### ISSUE TITLE
wanted to add 2 new features in the mini-magnum code, 1.save answer in .txt 2. display current date and time 

### ISSUE THREAD

**Issue by satyamroy001** [Magnum-Math/Magnum#12]
if my proposal is approved i will edit the codes in jupyter (only for mini-magnum) and also write the proper documentation

regards 
satyam roy

**Comment by Shreenabh664** [comment]
Hey sorry for the late reply! 

As far as saving the answer in .txt is concerned, that already happens in the full version of Magnum and cannot be shipped with Magnum Lite.

Displaying current date and time won't help much in a mathematical context in my opinion.

Also, we feel that the community documentation is sufficient enough to ensure smooth functioning.
