### ISSUE TITLE
Kerning error

### ISSUE THREAD

**Issue by quark67** [Magnum-Math/Magnum#13]
On the video published by @Shreenabh664 on Twitter (https://twitter.com/shreenabha/status/1294652394739912704), at 0 minutes 31 seconds, we can see a kerning error in the text. See https://en.wikipedia.org/wiki/Kerning about kerning.

We can see too space between "T" and "a" in "Taking", and too space between "l" and "f" in "half".

Sample .tex code:

```tex
\documentclass{article}
\begin{document}
	\emph{Taking half derivative}
	
	$Taking\:half\:derivative$
	
	$\mathit{Taking\:half\:derivative}$
\end{document}
```

Result:
![image](https://user-images.githubusercontent.com/9338576/90925656-ea8db380-e3f1-11ea-9097-9f810c987c43.png)

The first and third lines are correct, the second is very ugly typography. For italic text, if you cannot be in text mode, you must use `\mathit` (and `\:` for medium spaces between words). In math mode, `$word$` is the multiplication of the variables "w", "o", "r" and "d", and `$\mathit{word}$` is the italicized word "word".

**Comment by Shreenabh664** [comment]
Sure! The simple reason for this was treating text as a Math element and comes as a choice for the user.

There is a full section dedicated to this on our website magnum.shreenabh.com

A simple fix for this is to enclose any text in \text{Taking half derivative}.
