### ISSUE TITLE
Magnum Lite graphing

### ISSUE THREAD

**Issue by nicwineburger** [Magnum-Math/Magnum#14]
Hello, this isn't covered in https://magnum.shreenabh.com/ but could someone point me to an example of using Magnum Lite to display a graph? What is the syntax for getting a plot to generate from latex.txt? None of solutions I've come up with have worked, the 4th code box in Magnum Lite returns always returns this when asking it to graph something.  
![image](https://user-images.githubusercontent.com/26394153/90933578-c7e9a380-e3cd-11ea-85df-1c63ee902969.png)
 
The latex for this is extremely simple: f(x) = \sin{x}, I've also tried just \sin{x}, y = \sin{x}, sin(x), and all permutations of those options with no success. 

Any help would be greatly appreciated!

**Comment by Shreenabh664** [comment]
Replied in email.
